// <auto-generated />
using System;
using DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DAL.Models.VehicleMake", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abrv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VehicleModelID");

                    b.ToTable("VehicleMakes");
                });

            modelBuilder.Entity("DAL.Models.VehicleModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abrv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("DAL.Models.VehicleMake", b =>
                {
                    b.HasOne("DAL.Models.VehicleModel", "VehicleModel")
                        .WithMany("VehicleMakes")
                        .HasForeignKey("VehicleModelID");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("DAL.Models.VehicleModel", b =>
                {
                    b.Navigation("VehicleMakes");
                });
#pragma warning restore 612, 618
        }
    }
}
